# Generated by Django 2.2.3 on 2019-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='상품명')),
                ('stuck', models.IntegerField(verbose_name='재고')),
                ('description', models.DateTimeField(auto_now_add=True, verbose_name='상품설명')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'fastcampus_product',
            },
        ),
    ]
