# Generated by Django 2.2.3 on 2019-07-22 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190722_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='상품설명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='상품설명'),
        ),
    ]
